import streamlit as st
import streamlit.components.v1 as components
import networkx as nx
from pyvis.network import Network
from IPython.core.display import display, HTML

net = Network(notebook = True, cdn_resources="remote",height="900px", width="90%", select_menu = True, filter_menu=True,font_color="white", bgcolor = "black")

net.add_node('Node 27 - Patient Global Impression of Change [PGIC]',
              title='Patient Global Impression of Change [PGIC]', color='#e07c3e')

net.add_nodes(["Transition from Acute to Chronic Pain After Thoracic Surgery",
"COMEBACK",
"Development, Evaluation and Translation of Robotic Apparel for Alleviating Low Back Pain",
"Focused Ultrasound Neuromodulation of Dorsal Root Ganglion for Noninvasive Mitigation of Low Back Pain",
"HEALing LB3P: Profiling Biomechanical, Biological and Behavioral Phenotypes",
"Imaging Epigenetic Dysregulation in Patients with Low Back Pain",
"Nonpharmacologic Pain Management for Lumbar Surgery",
"Novel Imaging of Endplate Biomarkers in Chronic Low Back Pain",
"Proof of Concept Study to Treat Negative Affect in Chronic Low Back Pain",
"Randomized-controlled trial of virtual reality for chronic lower back pain to improve patient-reported outcomes and physical activity",
"Technology Research Site for Advanced, Faster Quantitative Imaging for BACPAC",
"The Spine Phenome Project: Enabling Technology for Personalized Medicine",
"UM MRC BACPAC",
"Wearable nanocomposite sensor system for diagnosing mechanical sources of low back pain and guiding rehabilitation",
"Biomarker Signature to Predict the Persistence of Post-Traumatic Headache",
"Discovery and Analytical Validation of Inflammatory Bio-Signatures of the Human Pain Experience",
"Discovery of Biomarker Signatures Prognostic for Neuropathic Pain after Acute Spinal Cord Injury",
"Mentoring in Discovery and Validation of Clinical Chronic Pain Biomarkers",
"Multi-Omic Biomarkers for Neuropathic Pain Secondary to Chemotherapy",
"SPRINT: Signature for Pain Recovery IN Teens",
"SurgeryPal",
"Validation of a novel cortical biomarker signature for pain",
"A Study to Evaluate the Safety and Efficacy of CNTX-6970 in Subjects With Knee Osteoarthritis Pain",
"EPPIC-Net: Novaremed Painful Diabetic Peripheral Neuropathy ISA (EN21-01)",
"EPPIC-Net: Platform Protocol to Assess Treatments for Painful Diabetic Peripheral Neuropathy",
"A sequenced-strategy for improving outcomes in patients with knee osteoarthritis pain",
"Integrated Treatment for Veterans with Co-Occurring Chronic Pain and Opioid Use Disorder",
"Optimizing the use of ketamine to reduce chronic postsurgical pain",
"Pain Response Evaluation of a Combined Intervention to Cope Effectively (PRECICE)",
"RESOLVE- Tailored Non-Pharmacotherapy Services for Chronic Pain: Testing Scalable and Pragmatic Approaches",
"Wake Forest NCORP Research Base",
'Achieving Equity through SocioCulturally-informed, Digitally-Enabled Cancer Pain managemeNT" (ASCENT) Clinical Trial',
"Addressing the chronic pain epidemic among older adults in underserved community center; The GetActive+ study",
"Culturally adapted mobile treatment of chronic pain in adolescent survivors of pediatric bone sarcoma",
"Equity Using Interventions for Pain and Depression (EQUIPD)",
"Group-based Integrative Pain Management: A multi-level approach to address intersectional stigma and social isolation in diverse primary care safety net patients with chronic pain",
"Integrating Nonpharmacologic Strategies for Pain with Inclusion, Respect, and Equity (INSPIRE): Tailored digital tools, telehealth coaching, and primary care coordination",
"Integrative Training Program for Pediatric Sickle Cell Pain",
"Latinx Children and Surgery",
"Partners for Pain & Wellbeing Equity: A Randomized Trial of Community Supported Complementary and Integrative Health Self Management for Back Pain",
"A Randomized Clinical Trial to Evaluate Non-Pharmacologic and Pharmacologic Approaches for Reducing Pain and Opioid Use Among Patients Treated with Maintenance Hemodialysis",
"Healing Opioid Misuse and Pain Through Engagement (HOPE) Trial",
"Implementation and Effectiveness of Mindfulness Oriented Recovery Enhancement as an Adjunct to Methadone Treatment for Opioid Use Disorder",
"Intergrated Care for Chronic Pain and Opioid Use Disorder: The IMPOWR Research Center at Montefiore/Einstein (IMPOWR-ME)",
"Pain Care At Home to Amplify Function (Pain CHAMP)",
"Randomized Clinical Trial Intervention to Treat Chronic Pain Among Persons Maintained on Methadone for Opioid Use Disorder",
"Stepped Care for Patients to Optimize Whole Recovery (SC-POWR)",
"Tailored Retention and Engagement for Equitable Treatment of OUD and Pain (TREETOP)",
"From Nerve to Brain: Toward a Mechanistic Understanding of Spinal Cord Stimulation in Human Subjects",
"RM1 Project 1: Evaluating the specific role of endogenous opioids as the mechanism underlying tAN-based analgesia in healthy individuals",
"RM1 Project 2: Determining the independent and synergistic effects of transcutaneous auricular neurostimulation (tAN) on direct brain activation in healthy individuals",
"Understanding the Mechanistic, Neurophysiological, and Antinociceptive Effects of Transcutaneous Auricular Neurostimulation for Treatment of Chronic Pain",
"Development and identification of magnetic resonance, electrophysiological, and fiber-optic imaging biomarkers of myofascial pain",
"Development and Validation of a Noninvasive Multimodal Ultrasound-Based Imaging Biomarker for Myofascial Pain",
"HEAL Initiative: Developing Quantitative Imaging and Other Relevant Biomarkers of Myofascial Tissues for Clinical Pain Management",
"MRI-based quantitative characterization of impaired myofascial interface properties in myofascial pain syndrome",
"Multimodal imaging biomarkers for investigating fascia, muscle and vasculature in myofascial pain",
"Quantifying and Treating Myofascial Dysfunction in Post Stroke Shoulder Pain",
"Total-body PET for assessing myofascial pain",
"Harvard PRECISION Human Pain Center",
"Human Nociceptor and Spinal Cord Molecular Signature Center",
"INTERCEPT: Integrated Research Center for human Pain Tissues",
"Fibromyalgia TENS in Physical Therapy Study (TIPS):an embedded pragmatic clinical trial",
"Group-Based Mindfulness for Patients with Chronic Low Back Pain in the Primary Care",
"Hybrid Effectiveness-Implementation Trial of Guided Relaxation and Acupuncture for Chronic Sickle Cell Disease Pain",
"Nonpharmacologic Pain Management for Lumbar Surgery",
"Non-pharmacological Options in postoperative Hospital-based And Rehabilitation pain Management (NOHARM) pragmatic clinical trial",
"Pragmatic Trial of Acupuncture for Chronic Low Back Pain in Older Adult",
"Comprehensive functional phenotyping of trigeminal neurons innervating temporomandibular joint (TMJ) tissues in male, female and aged mice, primates, and humans with and without TMJ disorders (TMJD)",
"Innervation of the knee and TMJ",
"Mapping the joint-nerve interactome of the knee",
"Neural architecture of the murine and human temporomandibular joint"],
              title = ["Transition from Acute to Chronic Pain After Thoracic Surgery",
"COMEBACK",
"Development, Evaluation and Translation of Robotic Apparel for Alleviating Low Back Pain",
"Focused Ultrasound Neuromodulation of Dorsal Root Ganglion for Noninvasive Mitigation of Low Back Pain",
"HEALing LB3P: Profiling Biomechanical, Biological and Behavioral Phenotypes",
"Imaging Epigenetic Dysregulation in Patients with Low Back Pain",
"Nonpharmacologic Pain Management for Lumbar Surgery",
"Novel Imaging of Endplate Biomarkers in Chronic Low Back Pain",
"Proof of Concept Study to Treat Negative Affect in Chronic Low Back Pain",
"Randomized-controlled trial of virtual reality for chronic lower back pain to improve patient-reported outcomes and physical activity",
"Technology Research Site for Advanced, Faster Quantitative Imaging for BACPAC",
"The Spine Phenome Project: Enabling Technology for Personalized Medicine",
"UM MRC BACPAC",
"Wearable nanocomposite sensor system for diagnosing mechanical sources of low back pain and guiding rehabilitation",
"Biomarker Signature to Predict the Persistence of Post-Traumatic Headache",
"Discovery and Analytical Validation of Inflammatory Bio-Signatures of the Human Pain Experience",
"Discovery of Biomarker Signatures Prognostic for Neuropathic Pain after Acute Spinal Cord Injury",
"Mentoring in Discovery and Validation of Clinical Chronic Pain Biomarkers",
"Multi-Omic Biomarkers for Neuropathic Pain Secondary to Chemotherapy",
"SPRINT: Signature for Pain Recovery IN Teens",
"SurgeryPal",
"Validation of a novel cortical biomarker signature for pain",
"A Study to Evaluate the Safety and Efficacy of CNTX-6970 in Subjects With Knee Osteoarthritis Pain",
"EPPIC-Net: Novaremed Painful Diabetic Peripheral Neuropathy ISA (EN21-01)",
"EPPIC-Net: Platform Protocol to Assess Treatments for Painful Diabetic Peripheral Neuropathy",
"A sequenced-strategy for improving outcomes in patients with knee osteoarthritis pain",
"Integrated Treatment for Veterans with Co-Occurring Chronic Pain and Opioid Use Disorder",
"Optimizing the use of ketamine to reduce chronic postsurgical pain",
"Pain Response Evaluation of a Combined Intervention to Cope Effectively (PRECICE)",
"RESOLVE- Tailored Non-Pharmacotherapy Services for Chronic Pain: Testing Scalable and Pragmatic Approaches",
"Wake Forest NCORP Research Base",
'Achieving Equity through SocioCulturally-informed, Digitally-Enabled Cancer Pain managemeNT" (ASCENT) Clinical Trial',
"Addressing the chronic pain epidemic among older adults in underserved community center; The GetActive+ study",
"Culturally adapted mobile treatment of chronic pain in adolescent survivors of pediatric bone sarcoma",
"Equity Using Interventions for Pain and Depression (EQUIPD)",
"Group-based Integrative Pain Management: A multi-level approach to address intersectional stigma and social isolation in diverse primary care safety net patients with chronic pain",
"Integrating Nonpharmacologic Strategies for Pain with Inclusion, Respect, and Equity (INSPIRE): Tailored digital tools, telehealth coaching, and primary care coordination",
"Integrative Training Program for Pediatric Sickle Cell Pain",
"Latinx Children and Surgery",
"Partners for Pain & Wellbeing Equity: A Randomized Trial of Community Supported Complementary and Integrative Health Self Management for Back Pain",
"A Randomized Clinical Trial to Evaluate Non-Pharmacologic and Pharmacologic Approaches for Reducing Pain and Opioid Use Among Patients Treated with Maintenance Hemodialysis",
"Healing Opioid Misuse and Pain Through Engagement (HOPE) Trial",
"Implementation and Effectiveness of Mindfulness Oriented Recovery Enhancement as an Adjunct to Methadone Treatment for Opioid Use Disorder",
"Intergrated Care for Chronic Pain and Opioid Use Disorder: The IMPOWR Research Center at Montefiore/Einstein (IMPOWR-ME)",
"Pain Care At Home to Amplify Function (Pain CHAMP)",
"Randomized Clinical Trial Intervention to Treat Chronic Pain Among Persons Maintained on Methadone for Opioid Use Disorder",
"Stepped Care for Patients to Optimize Whole Recovery (SC-POWR)",
"Tailored Retention and Engagement for Equitable Treatment of OUD and Pain (TREETOP)",
"From Nerve to Brain: Toward a Mechanistic Understanding of Spinal Cord Stimulation in Human Subjects",
"RM1 Project 1: Evaluating the specific role of endogenous opioids as the mechanism underlying tAN-based analgesia in healthy individuals",
"RM1 Project 2: Determining the independent and synergistic effects of transcutaneous auricular neurostimulation (tAN) on direct brain activation in healthy individuals",
"Understanding the Mechanistic, Neurophysiological, and Antinociceptive Effects of Transcutaneous Auricular Neurostimulation for Treatment of Chronic Pain",
"Development and identification of magnetic resonance, electrophysiological, and fiber-optic imaging biomarkers of myofascial pain",
"Development and Validation of a Noninvasive Multimodal Ultrasound-Based Imaging Biomarker for Myofascial Pain",
"HEAL Initiative: Developing Quantitative Imaging and Other Relevant Biomarkers of Myofascial Tissues for Clinical Pain Management",
"MRI-based quantitative characterization of impaired myofascial interface properties in myofascial pain syndrome",
"Multimodal imaging biomarkers for investigating fascia, muscle and vasculature in myofascial pain",
"Quantifying and Treating Myofascial Dysfunction in Post Stroke Shoulder Pain",
"Total-body PET for assessing myofascial pain",
"Harvard PRECISION Human Pain Center",
"Human Nociceptor and Spinal Cord Molecular Signature Center",
"INTERCEPT: Integrated Research Center for human Pain Tissues",
"Fibromyalgia TENS in Physical Therapy Study (TIPS):an embedded pragmatic clinical trial",
"Group-Based Mindfulness for Patients with Chronic Low Back Pain in the Primary Care",
"Hybrid Effectiveness-Implementation Trial of Guided Relaxation and Acupuncture for Chronic Sickle Cell Disease Pain",
"Nonpharmacologic Pain Management for Lumbar Surgery",
"Non-pharmacological Options in postoperative Hospital-based And Rehabilitation pain Management (NOHARM) pragmatic clinical trial",
"Pragmatic Trial of Acupuncture for Chronic Low Back Pain in Older Adult",
"Comprehensive functional phenotyping of trigeminal neurons innervating temporomandibular joint (TMJ) tissues in male, female and aged mice, primates, and humans with and without TMJ disorders (TMJD)",
"Innervation of the knee and TMJ",
"Mapping the joint-nerve interactome of the knee",
"Neural architecture of the murine and human temporomandibular joint"], 
              label = ["Transition from Acute to Chronic Pain After Thoracic Surgery",
"COMEBACK",
"Development, Evaluation and Translation of Robotic Apparel for Alleviating Low Back Pain",
"Focused Ultrasound Neuromodulation of Dorsal Root Ganglion for Noninvasive Mitigation of Low Back Pain",
"HEALing LB3P: Profiling Biomechanical, Biological and Behavioral Phenotypes",
"Imaging Epigenetic Dysregulation in Patients with Low Back Pain",
"Nonpharmacologic Pain Management for Lumbar Surgery",
"Novel Imaging of Endplate Biomarkers in Chronic Low Back Pain",
"Proof of Concept Study to Treat Negative Affect in Chronic Low Back Pain",
"Randomized-controlled trial of virtual reality for chronic lower back pain to improve patient-reported outcomes and physical activity",
"Technology Research Site for Advanced, Faster Quantitative Imaging for BACPAC",
"The Spine Phenome Project: Enabling Technology for Personalized Medicine",
"UM MRC BACPAC",
"Wearable nanocomposite sensor system for diagnosing mechanical sources of low back pain and guiding rehabilitation",
"Biomarker Signature to Predict the Persistence of Post-Traumatic Headache",
"Discovery and Analytical Validation of Inflammatory Bio-Signatures of the Human Pain Experience",
"Discovery of Biomarker Signatures Prognostic for Neuropathic Pain after Acute Spinal Cord Injury",
"Mentoring in Discovery and Validation of Clinical Chronic Pain Biomarkers",
"Multi-Omic Biomarkers for Neuropathic Pain Secondary to Chemotherapy",
"SPRINT: Signature for Pain Recovery IN Teens",
"SurgeryPal",
"Validation of a novel cortical biomarker signature for pain",
"A Study to Evaluate the Safety and Efficacy of CNTX-6970 in Subjects With Knee Osteoarthritis Pain",
"EPPIC-Net: Novaremed Painful Diabetic Peripheral Neuropathy ISA (EN21-01)",
"EPPIC-Net: Platform Protocol to Assess Treatments for Painful Diabetic Peripheral Neuropathy",
"A sequenced-strategy for improving outcomes in patients with knee osteoarthritis pain",
"Integrated Treatment for Veterans with Co-Occurring Chronic Pain and Opioid Use Disorder",
"Optimizing the use of ketamine to reduce chronic postsurgical pain",
"Pain Response Evaluation of a Combined Intervention to Cope Effectively (PRECICE)",
"RESOLVE- Tailored Non-Pharmacotherapy Services for Chronic Pain: Testing Scalable and Pragmatic Approaches",
"Wake Forest NCORP Research Base",
'Achieving Equity through SocioCulturally-informed, Digitally-Enabled Cancer Pain managemeNT" (ASCENT) Clinical Trial',
"Addressing the chronic pain epidemic among older adults in underserved community center; The GetActive+ study",
"Culturally adapted mobile treatment of chronic pain in adolescent survivors of pediatric bone sarcoma",
"Equity Using Interventions for Pain and Depression (EQUIPD)",
"Group-based Integrative Pain Management: A multi-level approach to address intersectional stigma and social isolation in diverse primary care safety net patients with chronic pain",
"Integrating Nonpharmacologic Strategies for Pain with Inclusion, Respect, and Equity (INSPIRE): Tailored digital tools, telehealth coaching, and primary care coordination",
"Integrative Training Program for Pediatric Sickle Cell Pain",
"Latinx Children and Surgery",
"Partners for Pain & Wellbeing Equity: A Randomized Trial of Community Supported Complementary and Integrative Health Self Management for Back Pain",
"A Randomized Clinical Trial to Evaluate Non-Pharmacologic and Pharmacologic Approaches for Reducing Pain and Opioid Use Among Patients Treated with Maintenance Hemodialysis",
"Healing Opioid Misuse and Pain Through Engagement (HOPE) Trial",
"Implementation and Effectiveness of Mindfulness Oriented Recovery Enhancement as an Adjunct to Methadone Treatment for Opioid Use Disorder",
"Intergrated Care for Chronic Pain and Opioid Use Disorder: The IMPOWR Research Center at Montefiore/Einstein (IMPOWR-ME)",
"Pain Care At Home to Amplify Function (Pain CHAMP)",
"Randomized Clinical Trial Intervention to Treat Chronic Pain Among Persons Maintained on Methadone for Opioid Use Disorder",
"Stepped Care for Patients to Optimize Whole Recovery (SC-POWR)",
"Tailored Retention and Engagement for Equitable Treatment of OUD and Pain (TREETOP)",
"From Nerve to Brain: Toward a Mechanistic Understanding of Spinal Cord Stimulation in Human Subjects",
"RM1 Project 1: Evaluating the specific role of endogenous opioids as the mechanism underlying tAN-based analgesia in healthy individuals",
"RM1 Project 2: Determining the independent and synergistic effects of transcutaneous auricular neurostimulation (tAN) on direct brain activation in healthy individuals",
"Understanding the Mechanistic, Neurophysiological, and Antinociceptive Effects of Transcutaneous Auricular Neurostimulation for Treatment of Chronic Pain",
"Development and identification of magnetic resonance, electrophysiological, and fiber-optic imaging biomarkers of myofascial pain",
"Development and Validation of a Noninvasive Multimodal Ultrasound-Based Imaging Biomarker for Myofascial Pain",
"HEAL Initiative: Developing Quantitative Imaging and Other Relevant Biomarkers of Myofascial Tissues for Clinical Pain Management",
"MRI-based quantitative characterization of impaired myofascial interface properties in myofascial pain syndrome",
"Multimodal imaging biomarkers for investigating fascia, muscle and vasculature in myofascial pain",
"Quantifying and Treating Myofascial Dysfunction in Post Stroke Shoulder Pain",
"Total-body PET for assessing myofascial pain",
"Harvard PRECISION Human Pain Center",
"Human Nociceptor and Spinal Cord Molecular Signature Center",
"INTERCEPT: Integrated Research Center for human Pain Tissues",
"Fibromyalgia TENS in Physical Therapy Study (TIPS):an embedded pragmatic clinical trial",
"Group-Based Mindfulness for Patients with Chronic Low Back Pain in the Primary Care",
"Hybrid Effectiveness-Implementation Trial of Guided Relaxation and Acupuncture for Chronic Sickle Cell Disease Pain",
"Nonpharmacologic Pain Management for Lumbar Surgery",
"Non-pharmacological Options in postoperative Hospital-based And Rehabilitation pain Management (NOHARM) pragmatic clinical trial",
"Pragmatic Trial of Acupuncture for Chronic Low Back Pain in Older Adult",
"Comprehensive functional phenotyping of trigeminal neurons innervating temporomandibular joint (TMJ) tissues in male, female and aged mice, primates, and humans with and without TMJ disorders (TMJD)",
"Innervation of the knee and TMJ",
"Mapping the joint-nerve interactome of the knee",
"Neural architecture of the murine and human temporomandibular joint"],
              shape = ['text', 'text','text','text','text','text',
            'text','text','text','text','text',
            'text','text','text','text','text',
            'text','text','text','text','text',
            'text','text','text','text', 'text','text','text','text','text',
            'text','text','text','text','text',
            'text','text','text','text','text','text',
                      'text','text','text','text','text',
            'text','text','text','text', 'text','text','text','text','text',
            'text','text','text','text','text',
            'text','text','text','text','text','text',
                      'text','text','text','text','text','text']
             )


edge_list = ["Transition from Acute to Chronic Pain After Thoracic Surgery",
"COMEBACK",
"Development, Evaluation and Translation of Robotic Apparel for Alleviating Low Back Pain",
"Focused Ultrasound Neuromodulation of Dorsal Root Ganglion for Noninvasive Mitigation of Low Back Pain",
"HEALing LB3P: Profiling Biomechanical, Biological and Behavioral Phenotypes",
"Imaging Epigenetic Dysregulation in Patients with Low Back Pain",
"Nonpharmacologic Pain Management for Lumbar Surgery",
"Novel Imaging of Endplate Biomarkers in Chronic Low Back Pain",
"Proof of Concept Study to Treat Negative Affect in Chronic Low Back Pain",
"Randomized-controlled trial of virtual reality for chronic lower back pain to improve patient-reported outcomes and physical activity",
"Technology Research Site for Advanced, Faster Quantitative Imaging for BACPAC",
"The Spine Phenome Project: Enabling Technology for Personalized Medicine",
"UM MRC BACPAC",
"Wearable nanocomposite sensor system for diagnosing mechanical sources of low back pain and guiding rehabilitation",
"Biomarker Signature to Predict the Persistence of Post-Traumatic Headache",
"Discovery and Analytical Validation of Inflammatory Bio-Signatures of the Human Pain Experience",
"Discovery of Biomarker Signatures Prognostic for Neuropathic Pain after Acute Spinal Cord Injury",
"Mentoring in Discovery and Validation of Clinical Chronic Pain Biomarkers",
"Multi-Omic Biomarkers for Neuropathic Pain Secondary to Chemotherapy",
"SPRINT: Signature for Pain Recovery IN Teens",
"SurgeryPal",
"Validation of a novel cortical biomarker signature for pain",
"A Study to Evaluate the Safety and Efficacy of CNTX-6970 in Subjects With Knee Osteoarthritis Pain",
"EPPIC-Net: Novaremed Painful Diabetic Peripheral Neuropathy ISA (EN21-01)",
"EPPIC-Net: Platform Protocol to Assess Treatments for Painful Diabetic Peripheral Neuropathy",
"A sequenced-strategy for improving outcomes in patients with knee osteoarthritis pain",
"Integrated Treatment for Veterans with Co-Occurring Chronic Pain and Opioid Use Disorder",
"Optimizing the use of ketamine to reduce chronic postsurgical pain",
"Pain Response Evaluation of a Combined Intervention to Cope Effectively (PRECICE)",
"RESOLVE- Tailored Non-Pharmacotherapy Services for Chronic Pain: Testing Scalable and Pragmatic Approaches",
"Wake Forest NCORP Research Base",
'Achieving Equity through SocioCulturally-informed, Digitally-Enabled Cancer Pain managemeNT" (ASCENT) Clinical Trial',
"Addressing the chronic pain epidemic among older adults in underserved community center; The GetActive+ study",
"Culturally adapted mobile treatment of chronic pain in adolescent survivors of pediatric bone sarcoma",
"Equity Using Interventions for Pain and Depression (EQUIPD)",
"Group-based Integrative Pain Management: A multi-level approach to address intersectional stigma and social isolation in diverse primary care safety net patients with chronic pain",
"Integrating Nonpharmacologic Strategies for Pain with Inclusion, Respect, and Equity (INSPIRE): Tailored digital tools, telehealth coaching, and primary care coordination",
"Integrative Training Program for Pediatric Sickle Cell Pain",
"Latinx Children and Surgery",
"Partners for Pain & Wellbeing Equity: A Randomized Trial of Community Supported Complementary and Integrative Health Self Management for Back Pain",
"A Randomized Clinical Trial to Evaluate Non-Pharmacologic and Pharmacologic Approaches for Reducing Pain and Opioid Use Among Patients Treated with Maintenance Hemodialysis",
"Healing Opioid Misuse and Pain Through Engagement (HOPE) Trial",
"Implementation and Effectiveness of Mindfulness Oriented Recovery Enhancement as an Adjunct to Methadone Treatment for Opioid Use Disorder",
"Intergrated Care for Chronic Pain and Opioid Use Disorder: The IMPOWR Research Center at Montefiore/Einstein (IMPOWR-ME)",
"Pain Care At Home to Amplify Function (Pain CHAMP)",
"Randomized Clinical Trial Intervention to Treat Chronic Pain Among Persons Maintained on Methadone for Opioid Use Disorder",
"Stepped Care for Patients to Optimize Whole Recovery (SC-POWR)",
"Tailored Retention and Engagement for Equitable Treatment of OUD and Pain (TREETOP)",
"From Nerve to Brain: Toward a Mechanistic Understanding of Spinal Cord Stimulation in Human Subjects",
"RM1 Project 1: Evaluating the specific role of endogenous opioids as the mechanism underlying tAN-based analgesia in healthy individuals",
"RM1 Project 2: Determining the independent and synergistic effects of transcutaneous auricular neurostimulation (tAN) on direct brain activation in healthy individuals",
"Understanding the Mechanistic, Neurophysiological, and Antinociceptive Effects of Transcutaneous Auricular Neurostimulation for Treatment of Chronic Pain",
"Development and identification of magnetic resonance, electrophysiological, and fiber-optic imaging biomarkers of myofascial pain",
"Development and Validation of a Noninvasive Multimodal Ultrasound-Based Imaging Biomarker for Myofascial Pain",
"HEAL Initiative: Developing Quantitative Imaging and Other Relevant Biomarkers of Myofascial Tissues for Clinical Pain Management",
"MRI-based quantitative characterization of impaired myofascial interface properties in myofascial pain syndrome",
"Multimodal imaging biomarkers for investigating fascia, muscle and vasculature in myofascial pain",
"Quantifying and Treating Myofascial Dysfunction in Post Stroke Shoulder Pain",
"Total-body PET for assessing myofascial pain",
"Harvard PRECISION Human Pain Center",
"Human Nociceptor and Spinal Cord Molecular Signature Center",
"INTERCEPT: Integrated Research Center for human Pain Tissues",
"Fibromyalgia TENS in Physical Therapy Study (TIPS):an embedded pragmatic clinical trial",
"Group-Based Mindfulness for Patients with Chronic Low Back Pain in the Primary Care",
"Hybrid Effectiveness-Implementation Trial of Guided Relaxation and Acupuncture for Chronic Sickle Cell Disease Pain",
"Nonpharmacologic Pain Management for Lumbar Surgery",
"Non-pharmacological Options in postoperative Hospital-based And Rehabilitation pain Management (NOHARM) pragmatic clinical trial",
"Pragmatic Trial of Acupuncture for Chronic Low Back Pain in Older Adult",
"Comprehensive functional phenotyping of trigeminal neurons innervating temporomandibular joint (TMJ) tissues in male, female and aged mice, primates, and humans with and without TMJ disorders (TMJD)",
"Innervation of the knee and TMJ",
"Mapping the joint-nerve interactome of the knee",
"Neural architecture of the murine and human temporomandibular joint"]

for item in edge_list:
    net.add_edge('Node 27 - Patient Global Impression of Change [PGIC]', item)

net.repulsion(spring_strength = 0)
net.show("edges.html")


# Save and read graph as HTML file (on Streamlit Sharing)
try:
    path = '/tmp'
    net.save_graph(f'{path}/pyvis_graph.html')
    HtmlFile = open(f'{path}/pyvis_graph.html', 'r', encoding='utf-8')

# Save and read graph as HTML file (locally)
except:
    path = '/html_files'
    net.save_graph(f'{path}/pyvis_graph.html')
    HtmlFile = open(f'{path}/pyvis_graph.html', 'r', encoding='utf-8')

# Load HTML file in HTML component for display on Streamlit page
components.html(HtmlFile.read(), height=1000, width = 1000)
